apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: "dblibros"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: dbservice
spec:
  ports:
    - port: 5432
  selector:
    app: dbservice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-libros
spec:
  replicas: 3
  selector:
    matchLabels:
      app: applibros
  template:
    metadata:
      labels:
        app: applibros
    spec:
      containers:
      - name: applibros
        image: ornelaanahi/applibros
        ports:
        - containerPort: 8080
        env:
        - name: hibernate__hbm2ddl__auto
          value: "create"
        - name: javax__persistence__jdbc__driver
          value: "org.postgresql.Driver"
        - name: javax__persistence__jdbc__password
          value: "123"
        - name: javax__persistence__jdbc__url
          value: "jdbc:postgresql://dbservice/dblibros"
        - name: javax__persistence__jdbc__user
          value: "postgres"
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: applibros
